### ISSUE TITLE
Can you support 1.17 Snapshot 20w46a?

### ISSUE THREAD

**Issue by wansn05** [samolego/GolfIV#1]
I try to made changes in gradle.properties and build.gradle according to the prompts in the [Fabric Versions](https://modmuss50.me/fabric.html?&version=20w46a) and migrated mappings to compile the 20w46a version, but it prompted me to make an error: abilities is private access control in PlayerEntity.          if(golfConfig.main.noFly && !player.abilities.allowFlying && !player.isClimbing()) {

So can you support 1.17 Snapshot 20w46a?

[Translate by Tencent Mr. Translator](https://fanyi.qq.com/)

**Comment by wanshanning** [comment]
Console screenshot
![image.png](https://i.loli.net/2020/11/24/AwLNZszpukEvHxl.png)

**Comment by samolego** [comment]
This is easy to implement, but ...

I still don't count the mod to be stable enough to be used. FPs are thrown all over the place 😄 .
*I'd like to release at least one stable version before porting it around to snapshots ...*

Don't get me wrong, after it's at least *a bit* stable and tested, I'd love to support the snapshots, but right now it means more work to do each week rather then spend time on debugging 😉 .

**Comment by wanshanning** [comment]
That's so great!

**Comment by wansn05** [comment]
nowclose this issue and wait for 1.17 version mod
：）

**Comment by wansn05** [comment]
nowclose this issue and wait for 1.17 version mod
：）
