### ISSUE TITLE
"Jetpack" Hack Works When Elytra is Activated

### ISSUE THREAD

**Issue by Some5** [samolego/GolfIV#10]
While I was testing I discovered that while in flight mode with a elytra on, you can use the "jetpack" hack to fly around without getting kicked. No idea if you are able to fix this, just thought I would let you know.

**Comment by supsm** [comment]
I don't think you actually get kicked for hacking yet... unsure if that has changed though.

**Comment by Some5** [comment]
It kicked me. I will test more.

**Comment by Some5** [comment]
It wasn't saying I was using fly hacks though.

**Comment by supsm** [comment]
Yeah, I've seen this as well (#6). I couldn't find the message because it wasn't actually in any of the logs. Kinda strange, but I guess it's ok for now. I've suggested a seperate log for hacks, so that might get implemented.

**Comment by Some5** [comment]
Yeah, the real issue is that it isn't detecting the hack.

**Comment by samolego** [comment]
When having elytra activated, flight check isn't active, since it's not been adapted for it (yet).

**Comment by samolego** [comment]
Since some tweaks were done here; elytra flight is now *usually* detected, but jetpack can still bypass it most of the time.
