### ISSUE TITLE
Players with high ping get falsely accused a lot

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#11]
This player had over 300 ping when this happened
![image](https://user-images.githubusercontent.com/60897356/103163182-8324ad80-47af-11eb-8e36-81b02156590d.png)
I've also seen it happen with timer hacks in the past.

Also I'm not sure if this player is actually hacking. It seems pretty sus that this all happened in the span of 1 second. However, with the timer hacks, it was confirmed that the player wasn't hacking. (mightve been fixed tho)

**Comment by samolego** [comment]
Timer hack is disabled atm, that's why it isn't throwing any detections :) ...

Thanks for reporting. I see I'll have to do more testing with clumsy.
