### ISSUE TITLE
Clicking on boats in portals is weird

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#12]
![2020-12-27_10 43 10](https://user-images.githubusercontent.com/60897356/103177564-73997900-4830-11eb-9cba-84cb05a56333.png)

Right clicking on this boat makes the mod think I'm using hitting through wall hacks (I'm not even hitting anything)

**Comment by samolego** [comment]
Thanks for pointing it out, I overlooked that. Should be fixed now.
