### ISSUE TITLE
Falling in a boat triggers fly hack

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#13]
I fell off a cliff in a boat for testing purposes, and it said that I was using fly hacks. It might be because boats fall slower, but I'm not sure.
![image](https://user-images.githubusercontent.com/60897356/103177827-beb48b80-4832-11eb-9545-71c0aec85ae1.png)

**Comment by supsm** [comment]
![2020-12-27_11 02 14](https://user-images.githubusercontent.com/60897356/103177851-020efa00-4833-11eb-9351-6db15e8c7bde.png)
this also triggers the vanilla anticheat lol

**Comment by samolego** [comment]
I'm closing this since vehicles will need an extra check.
