### ISSUE TITLE
Killaura detection issues & suggestion

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#14]
Sometimes the killaura detecting thing will be hit without using killaura.

Possible fixes:
- Make the killaura detector at the player's feet. This way they shouldn't be able to hit it, but if they do they'll probably kill themselves
- Always make the killaura detector behind the player. You will have to filter out other mobs/players, and also make sure they can actually hit the player
- Completely change the killaura detection so it detects if the entity they're trying to hit is something they're looking at (+-10° maybe)

Personally I prefer the last option, it seems less "quick and dirty" compared to what we currently have.

**Comment by samolego** [comment]
The last check is actually in already. The fake player will probably be invisible and toggleable.

**Comment by samolego** [comment]
Thinking of this more, maybe fake player should be used only when hit accuracy is above certain percentage? This prevents "scaring" of legit players and gives another opportunity to check the player for killaura hacks ..?

**Comment by supsm** [comment]
I just thought of something. What if they are using lookaura instead of killaura? If the fake player is behind then they wouldn't hit it, but if it was in front it would trigger falsely.

**Comment by samolego** [comment]
This is then a lot harder to detect ... Especially because we don't want false positives when killing mobs in a mob grinder etc.

**Comment by supsm** [comment]
yeah... would it be possible to see when the player is attacking? if it's right after the attack is recharged, then it probably is some sort of killaura type thing, especially if there isn't any that is close, but not exactly after the attack is recharged. Dunno, just an idea maybe
