### ISSUE TITLE
Bobbing in a bubble column

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#15]
Standing on the top of a soul sand bubble column makes the mod think I'm using fly hacks. I do not need to do anything, just standing there will trigger the mod. It will not activate at first, but it eventually will (probably because the player bobs higher over time). 
![2021-01-03_11 29 34](https://user-images.githubusercontent.com/60897356/103487111-c25a8c00-4db7-11eb-8e6a-f7841a8587f9.png)

**Comment by samolego** [comment]
Thanks for reporting! It seems like a need for a better in-water state detection.

**Comment by samolego** [comment]
This should be now fixed
