### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#2]
Elytra jumping causes the mod to think I'm hacking (maybe elytra movement control, not sure)
However, when using actual elytra movement hacks, it doesn't think I'm hacking...

**Comment by samolego** [comment]
wdym by `Elytra jumping`?

Anyway, you should disable it since it's more of an experiment atm ... You can see statuses of [check](https://samolego.github.io/GolfIV/javadoc/org/samo_lego/golfiv/storage/GolfConfig.Main.html#preventElytraHacks).

**Comment by supsm** [comment]
Nevermind, it says I was using NoFall/Jesus...
By elytra jumping I mean using the elytra in mid air while jumping and running forward... Not sure if that's clear

**Comment by supsm** [comment]
Also, I think lagging causes the mod to think that I am using timer hack

**Comment by samolego** [comment]
Oh, I see now.

Yep timer check should *not* be used ;)

**Comment by supsm** [comment]
Another thing I've noticed, when using NoFall it freezes the player in mid-air (then the player eventually gets kicked for flying). Guess it's just an added feature ;)

**Comment by samolego** [comment]
> Another thing I've noticed, when using NoFall it freezes the player in mid-air (then the player eventually gets kicked for flying). Guess it's just an added feature ;)

That's right, I'm still deciding whether to leave it in or not.

**Comment by supsm** [comment]
I think it should be left out until you find a solution to the elytra issue I've mentioned earlier. It messes up the elytra jumping by removing all momentum sometimes, which kind of ruins the point of elytra jumping.

**Comment by supsm** [comment]
Also, opening a chest while falling makes the mod think that I am using inventory hacks. I can definitely see where this is coming from, but maybe add an exception for moving downwards or something?
I think this may also cause issues if the player is sliding on ice or gliding with elytra but I haven't tested yet

**Comment by samolego** [comment]
I know about this, haven't been able to filter it out :). Kinda busy with irl stuff atm.

**Comment by supsm** [comment]
No problem! I've just tested gliding with elytra and opening inventory, and it didn't trigger the warning.

**Comment by supsm** [comment]
Noticed that it also happens when you're being pushed by other entities while you have an inventory open.

**Comment by supsm** [comment]
Also, I think activating elytra when swimming near the surface makes the mod think I'm using elytra movement hacks. 
I keep finding new issues, I'll just post them here when I find another one.

**Comment by supsm** [comment]
Another issue is than when players are sprint jumping in a 2-high tunnel (as a means to travel fast), the mod will think they are using speed hacks.

**Comment by supsm** [comment]
These issues seem to be fixed. Thanks!
