### ISSUE TITLE
Dying breaks the cheat log

### ISSUE THREAD

**Issue by SpaceClouds42** [samolego/GolfIV#21]
When player dies, their golf nbt is corrupted (I have yet to look at the playerdat file right before and right after death, will do tomorrow morning) If you do `/golf player @s seeCheatLog` after dying (without doing `clearCheatLog` first), you will get an "Unexpected error" (it's a NullPointerException when you hover over it).

**Comment by samolego** [comment]
Oh, I thought I already fixed it 🤔 . Will look into it once more, thanks for reporting.
