### ISSUE TITLE
Levitation Check does not work properly

### ISSUE THREAD

**Issue by SpaceClouds42** [samolego/GolfIV#22]
https://github.com/samolego/GolfIV/blob/fc40a58ea040dba7e4a37fb3ff1c27661b2e81a5/src/main/java/org/samo_lego/golfiv/mixin_checks/movement/ServerPlayNetworkHandlerMixin_FlightCheck.java#L62

I still receive false positives when "flying" around with levitation effect. I had effect level one, and it quickly set off fly hack detection and "kicked" me multiple times in 10 seconds of having levitation active.

**Comment by samolego** [comment]
Thanks for reporting! Did you have any other status effects?

**Comment by SpaceClouds42** [comment]
No, I was testing with only levitation

**Comment by samolego** [comment]
I placed the brackets wrongly ...
