### ISSUE TITLE
Suspicion value not being updated properly

### ISSUE THREAD

**Issue by SpaceClouds42** [samolego/GolfIV#23]
![image](https://user-images.githubusercontent.com/71787666/105219059-0245a100-5b24-11eb-9af3-aad678c89959.png)
The suspicion nbt tag is not being updated with the actual sus value

**Comment by samolego** [comment]
I think it's actually working as intended (tm). After suspicion value is higher than (default) 200, it is reset, player is kicked and number of kicks is increased by one.

**Comment by SpaceClouds42** [comment]
Oh, that would definitely explain that then
