### ISSUE TITLE
Crash on server boot

### ISSUE THREAD

**Issue by dandin87** [samolego/GolfIV#32]
All of Fabric 3 2.7.x Dev pack
Turns out we are starting to get some players using that book and quill dupe glitch, or more likely doing it with wurst. So figured it was time to test your mod out. Crash from the log https://paste.alloffabric.com/jexuviqefu.sql
Simply removing     "illegal_items.CompoundTagMixin_SizeCheck", from golfiv.mixins.json inside the jar allowed it to load. 

[00:11:02] [main/FATAL]: Mixin prepare failed preparing illegal_items.CompoundTagMixin_SizeCheck in golfiv.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'org.samo_lego.golfiv.mixin.illegal_items.CompoundTagMixin_SizeCheck' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'org.samo_lego.golfiv.mixin.illegal_items.CompoundTagMixin_SizeCheck' was not found

You have 5 mixins declared in your illegal_items part of golfiv.mixins.json 
    "illegal_items.CompoundTagMixin_SizeCheck",
    "illegal_items.ItemStackMixinCast_ItemStackChecker",
    "illegal_items.PlayerInventoryMixin_IllegalsCheckInsert",
    "illegal_items.ServerPlayNetworkHandlerMixin_CreativeItemsCheck",
    "illegal_items.ServerPlayNetworkHandlerMixin_IllegalsCheckSlot",
but you only have 4 of those mixins here 
https://github.com/samolego/GolfIV/tree/golfive/src/main/java/org/samo_lego/golfiv/mixin/illegal_items

**Comment by samolego** [comment]
Wait, you removed the class from the jar? It's totally logical that it crashes then ... 🤔 
If you don't need the check, just turn it off.

**Comment by dandin87** [comment]
No, you don't have a class in the mod. I removed the line in the golfiv.mixins.json after getting the error. Have you tested your released jar on a server? It does not boot....

**Comment by samolego** [comment]
Oh, I'm sorry 😞  ...
Yes, that's right, seems like I forgot to add the file to git as Spaceclouds has mentioned ...

**Comment by samolego** [comment]
It actually turned out that this was a temp mixin ... Thanks for reporting!
