### ISSUE TITLE
Suggestion: "Fix Overstacked Items Instead" config option

### ISSUE THREAD

**Issue by WaffleTraits** [samolego/GolfIV#37]
Similar to the [Illegal Item Stack Remove plugin](https://github.com/dniym/IllegalStack), having an option for fixing over stacked items instead of outright removing them would be a useful feature to have.

**Comment by samolego** [comment]
So instead of 1 "global" setting divide it into more specific ones? Agreed, that'd be beneficial.
Also shouldn't be too hard to do it ...

**Comment by cittyinthecloud** [comment]
Be careful if splitting overstacks, Mojang does it when breaking shulkers and ends up creating extra slots.

**Comment by samolego** [comment]
Closing as this was implemented.
