### ISSUE TITLE
Turtle Master Potions get turned into uncraftable potions

### ISSUE THREAD

**Issue by pelophone** [samolego/GolfIV#40]
Seems like turtle master potions and their variants get turned into 'uncraftable potions'. I expect this is golfiv trying to legalize the item, but I admittedly haven't done a lot of testing.
![tESbSIm 1](https://user-images.githubusercontent.com/85641978/121406152-adf45f80-c912-11eb-9d95-c0a0f568140b.png)

**Comment by samolego** [comment]
This might very likely be golfiv, thanks for reporting!

**Comment by samolego** [comment]
Meanwhile turn off the `checkPotionLevels` config option

**Comment by pelophone** [comment]
Thanks for the tip! Do I need to update to 0.3.2 to get that config option? And do I need to be on 1.17 to run that version?

**Comment by samolego** [comment]
Ah, yes, you'd need 1.17.
Otherwise disable the item legalise option.
