### ISSUE TITLE
AOF4 server can't start with GolfIV 0.3.2

### ISSUE THREAD

**Issue by irunatbullets** [samolego/GolfIV#44]
I noticed some suspicious disconnects after someone was looking for ink, so I wanted to add golfiv to the official aof4 server.

https://paste.alloffabric.com/ugitiqojol.yaml

**Comment by samolego** [comment]
Config is malformed around line `items.survival.checkEnchants`

**Comment by Ampflower** [comment]
Looking at the stack trace, it appears that your GolfIV config is damaged. Is `checkEnchants` properly set to `true` or `false` in `GolfIV_config.json`, and includes a trailing comma for the next line?
Example of what to look for:
![image](https://user-images.githubusercontent.com/8528256/122362177-c402b100-cf0c-11eb-8c0e-ef2f6716c152.png)

**Comment by irunatbullets** [comment]
Sorry, yeah it was a missing comma. Thank you.
