### ISSUE TITLE
Items in GUI menus lose their names with GolfIV installed

### ISSUE THREAD

**Issue by Fiznik** [samolego/GolfIV#48]
Happens with Patbox's Armorstand Editor And Potatoboy's HeadIndex

Most notable with HeadIndex if you're gonna recreate . All heads show as 'player head' with the Steve texture. While in armorstandeditor items just lose their name. (same issue really but affects headindex worse)

Its late so im writing this pretty quick but you should know I have very many other mods. However removing this in particular fixed it. 

If it doesnt recreate immediately tell me and I can probably find the modlist in a log somewhere. 

I havent changed anything in the golf config

**Comment by ghost** [comment]
same problem with golfiv and flan mod .. in /flan menu
