### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#5]
GolfIV causes my server to crash.
The old one I had was fine, this new one is not.

Crash report: 
[crash-2020-12-07_12.05.27-server.txt](https://github.com/samolego/GolfIV/files/5668524/crash-2020-12-07_12.05.27-server.txt)

Compiled jar (new):
[golfiv-0.0.1.zip](https://github.com/samolego/GolfIV/files/5668535/golfiv-0.0.1.zip)

Unfortunately I don't have the old jar.

**Comment by supsm** [comment]
Also, removing GolfIV causes the server to run fine.

**Comment by samolego** [comment]
`Caused by: java.lang.NullPointerException
	at org.geysermc.connector.utils.LocaleUtils.downloadLocale(LocaleUtils.java:148)`

This is a Geyser issue. Sounds like incompatibility. Does it happen without `killaura` checks?

**Comment by supsm** [comment]
Disabling geyser didn't seem to fix the issue... Unfortunately it did not generate a crash report, but here are the logs:
[latest.log](https://github.com/samolego/GolfIV/files/5674035/latest.log)

**Comment by samolego** [comment]
Oh, I left a debug mixin in mixin config.
