### ISSUE TITLE
Durability and enchantments are hidden

### ISSUE THREAD

**Issue by n194** [samolego/GolfIV#50]
Tested on 1.17.1 server with GolfIV 0.3.2 and Fabric API 0.36.1.

https://user-images.githubusercontent.com/67550725/126139719-007fb0f3-7fd5-46e1-b47d-646327386376.mp4

**Comment by saransh323** [comment]
Check the first comment by Samolego on #45. 
You just have to set ItemInverntoryKickPatch to false in the config to fix the issue, that's what I did.

**Comment by axxxzy** [comment]
yeah and this sucks cause this is the only anticheat i can find for fabric :( owners fix ur crap

**Comment by n194** [comment]
@axxxzy that’s not nice. samolego has graciously provided their work to the community and you can fork the project and fix your issues yourself, but your disrespect is not welcome here.

**Comment by samolego** [comment]
@axxxzy as mentioned above, we are all volunteers here. Everything that we do is done in our free time, please don't take it as granted.
