### ISSUE TITLE
"Kicked" players aren't actually kicked

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#6]
I was testing this mod, then at one point the server console said it kicked me. However, I did not leave the game, nor did it say that I left the game from the server console. I could open chests and load the world, but when I logged back in, what I did was not saved. Probably should just /kick them.

**Comment by samolego** [comment]
Kicking is still just a placeholder until #3 is resolved

**Comment by supsm** [comment]
The console said that it kicked me though... My data also wasn't saved after that.

**Comment by samolego** [comment]
Huh? What did it say? Was kick logged by `BallLogger` (the GolfIV logger?
)

**Comment by supsm** [comment]
I couldnt find the log file that had it, so I did it again. This is what it said:
![image](https://user-images.githubusercontent.com/60897356/102396674-a078a100-3f91-11eb-9938-629878b4f320.png)
Note that there's nothing after that. No "Kicked supsm: kicked by an operator" or "supsm left the game".

**Comment by samolego** [comment]
Yeah, as I said, this is just another message that *represents* kicking without doing anything. It has nothing to do with saving the progress.

**Comment by supsm** [comment]
Okay. It was probably just a coincidence then.
