### ISSUE TITLE
Inventory walk hack detection has a lot of false positives

### ISSUE THREAD

**Issue by supsm** [samolego/GolfIV#7]
The mod thinks I'm using inventory walk hacks a LOT. I think it occurs right when I open the chest/inventory, but I'm not sure. If this is the case, it could be that the player's momentum/lag could be causing this issue. Maybe try adding a delay (of say 0.5 seconds) when an inventory is opened before you check for movement?

**Comment by samolego** [comment]
Mod wasn't reseting the counter after closing inventory ... This should now be fixed
