### ISSUE TITLE
Can't breake blocks

### ISSUE THREAD

**Issue by KdGaming0** [samolego/GolfIV#72]
I have installed GolfiV on my server and after 2 minutes of joining it, I can't brake block it fix after reconnecting. 

The server is a 1.20 snapshot so that may be what is wrong but the mod is loading on server start.

**Comment by Ampflower** [comment]
Curious thing; do you by chance have spawn protection enabled on the server?

If so, are you op, or breaking blocks in the spawn chunks?

Vanilla will prevent block breaking near spawn if you have spawn protection enabled in server.properties.

If spawn protection is off, you're not at spawn or you're op'd, can you post a log from the server?
Be sure to strip out any IPs tho.

**Comment by KdGaming0** [comment]
> Curious thing; do you by chance have spawn protection enabled on the server?
> 
> If so, are you op, or breaking blocks in the spawn chunks?
> 
> Vanilla will prevent block breaking near spawn if you have spawn protection enabled in server.properties.
> 
> If spawn protection is off, you're not at spawn or you're op'd, can you post a log from the server? Be sure to strip out any IPs tho.

I am op and I have spawn protection off and are not anywhere near spawn.
In the server console nothing happened it only says that I am joining and nothing more.
Whit out the mod installed I can brake blocks.

**Comment by KdGaming0** [comment]
After logging in I take all from 30 sec to 5 min I can't brake blocks I can't type in chat ether but I can plays blocks.


![Screenshot 2023-04-11 121459](https://user-images.githubusercontent.com/97355992/231132363-b447840a-6d9a-4426-9651-124b6d32bcc8.png)
![Screenshot 2023-04-11 121426](https://user-images.githubusercontent.com/97355992/231132365-b35e6465-7359-4e9b-8a4f-7779e5d21866.png)

**Comment by Ampflower** [comment]
Likely will need a proper update to 1.20 then. May take a lil while depending on what Mojang has done. 

Also, you may have missed a line when censoring IPs.

**Comment by KdGaming0** [comment]
Ok. Tanks for the help. 
Hope an update to 1.20 comes soon as I need an anti cheat mod.

**Comment by KdGaming0** [comment]
Tanks
