### ISSUE TITLE
Player Data Not Saving

### ISSUE THREAD

**Issue by Some5** [samolego/GolfIV#9]
I was testing out the mod using Wurst Client, and I flew upward and got disconnected. After reconnecting I tried using a elytra with the "jetpack" hack to fly around, afterword I went to shut down the server and I noticed in the console:

"[15:28:01] [Server thread/WARN]: Failed to save player data for Blue_Dye"

After reconnecting and disconnecting a couple of times I found that I always respawned up in the air where I got disconnected. I have verified that player data is saved successfully without GolfIV. I have no other mods than GolfIV and fabric api. Log attached. Build is https://github.com/samolego/GolfIV/actions/runs/438107637.

[2020-12-26-3.log.gz](https://github.com/samolego/GolfIV/files/5743602/2020-12-26-3.log.gz)

**Comment by samolego** [comment]
Hi, thanks for reporting! I'll look into it when I have time 😉 .

**Comment by samolego** [comment]
Did you die during the test proccess? I think this might be one of the reasons ...

**Comment by samolego** [comment]
Forgot to close this on push :)
